---
title: "ch.03: 支配戦略と支配される戦略の繰り返し消去"
format: html
editor: source
---

## 3.1　不平等なじゃんけん
## 3.2　支配される戦略
## 3.3　支配される戦略の繰り返し消去
## 3.4　支配戦略
## 練習問題
## コラム：不平等なじゃんけんの教室実験
　
　
4. ナッシュ均衡
## 4.1　支配関係と最適反応
## 4.2　ナッシュ均衡
## 4.3　支配関係とナッシュ均衡
## 4.4　ナッシュ均衡への到達
練習問題
5. ナッシュ均衡の応用1: 協力と調整
## 5.1　囚人のジレンマ
## 5.2　共有地の悲劇
## 5.3　調整ゲーム
## 5.4　鹿狩りゲーム
## 5.5　n人鹿狩りゲーム
## 練習問題
## コラム：リスク支配均衡
6. 混合戦略ナッシュ均衡
## 6.1　ナッシュ均衡の存在しないゲーム
## 6.2　混合戦略
## 6.3　期待利得
## 6.4　混合戦略に対する最適反応
## 6.5　混合戦略ナッシュ均衡
## 6.6　混合戦略ナッシュ均衡の性質
## 6.7　サポート戦略の期待利得の同値性の応用
## 練習問題
## rgamer Tips: 図の色を変更する
7. 混合戦略ナッシュ均衡の実現プロセスとその解釈
## 7.1　混合戦略ナッシュ均衡に関する疑問
## 7.2　前期に対する最適反応
## 7.3　戦略の魅力度を修正するモデル
## 7.4　相手の選択確率を予想するモデル
## 7.5　信念学習と仮想プレイとの関係
## 練習問題
## rgamer Tips: sim_game()の使い方
8. ナッシュ均衡の応用2: 寡占市場の分析
## 8.1　独占・複占・寡占
## 8.2　クールノー競争
## 8.3　2値選択のケースの分析
## 8.4　連続値選択のケースの分析
## 8.5　比較静学
## 8.6　シミュレーション
## 8.7　ベルトラン競争
## 8.8　クールノー均衡の一般的なケース
## 練習問題
## コラム：懲罰に関するルール


9. 完全情報の展開形ゲーム
## 9.1　展開形ゲームとゲームの木
## 9.2　rgamerによるゲームの木の描画
## 9.3　完全情報ゲーム
## 9.4　完全情報の展開形ゲームを解く
## 練習問題
## rgamer Tips: ゲームの木の見た目を変更する
10. バックワードインダクションの応用1
## 10.1　Number 10
## 10.2　支配戦略のあるゲーム
## 10.3　シュタッケルベルク均衡
## 10.4　集合行為への参加
## 練習問題
## rgamer Tips: extensive_form()とseq_form()の関係
11. バックワードインダクションの応用2
## 11.1　最後通牒ゲーム
## 11.2　アウトサイドオプション
## 11.3　カウンターオファー
## 11.4　不平等回避
## 練習問題
## コラム：他者を思いやる選好の別の形
12. サブゲーム完全均衡
## 12.1　完全情報ゲームにおける戦略の概念とナッシュ均衡
## 12.2　情報集合
## 12.3　不完全情報ゲームにおける戦略の概念とナッシュ均衡
## 12.4　サブゲーム
## 12.5　サブゲーム完全均衡
## 12.6　サブゲームの縮約を使ったサブゲーム完全均衡の導出
## 練習問題
## コラム：繰り返し囚人のジレンマゲーム
第IV部　その他のトピック
13. マッチング
## 13.1　マッチングの問題
## 13.2　マッチング問題の定式化
## 13.3　ボストン(Boston)方式
## 13.4　受け入れ保留(deferred acceptance; DA)方式
## 13.5　耐戦略性
## 13.6　提案側と応答側のどちらが有利か
## 13.7　効率性と安定マッチング
## 練習問題
## rgamer Tips: matching()へ選好リストを渡す便利な方法
14. 行動調整と学習のモデル
## 14.1　最適反応動学
## 14.2　エラーを考慮した最適反応のモデル化
## 14.3　模倣動学
## 14.4　強化学習
## 14.5　信念学習
## 14.6　EWA