---
title: "Ch.02"
output: html_document
date: "2023-08-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
-\> メモ
<https://scrapbox.io/r-code/R%E3%81%AB%E3%82%88%E3%82%8B%E5%A4%9A%E5%A4%89%E9%87%8F%E8%A7%A3%E6%9E%90%E5%85%A5%E9%96%80>


# 欠損値の処理
```{r}
df
```


- 欠損のある行を削除
```{r}
na.omit(df)
```

#>   x  y
#> 1 1  0
#> 2 2 10

- 欠損のある行番号を取得
```{r}
complete.cases(df)
```

complete.cases(df)
```{r}
mat <- matrix(c(2,3,4,5,1,2,3,1,2), nrow = 3, ncol = 3)
mat
```

```{r}
# セル番号の出力
which(mat == 2)
# 行/列番号の出力
which(mat == 2, arr.ind = TRUE)
```
```{r}
loc_2 <- which(mat == 2, arr.ind = TRUE)
mat[loc_2] <- 10
mat
```

```{r}
A <- array(1:12, dim = 4:3)
cat("A =\n")
A

cat("sweep(A,1,5) =\n")
sweep(A, 1, 5, FUN = "-")

cat("apply(A, 1, min) =\n")
(A.min <- apply(A, 1, min))  # == 1:4
cat("sweep(A, 1, A.min) =\n")
sweep(A, 1, A.min)

cat("sweep(A, 1, A.min, FUN = '==') =\n")
sweep(A, 1, A.min, FUN = "==")
```







```{r}
list_data <- list(
  data.frame(
    a = 1:3,
    b = 2:4
  ),
  data.frame(
    a = 1:3,
    b = 2:4
  ),
  data.frame(
    a = 1:3,
    b = 2:4
  )
)
list_data

df_cbind <- data.frame(
  c = 5:7,
  d = 6:8
)
```

```{r}
# list形式の一つずつに対して cbind
lapply(list_data, cbind, df_cbind)

# list形式に対して一つずつrbindを適用する
do.call(rbind, list_data)
```


```{r}
list_data <- list(
  data.frame(
    a = 1:3,
    b = 2:4
  ),
  data.frame(
    a = 1:3,
    b = 2:4
  ),
  data.frame(
    a = 1:3,
    b = 2:4
  )
)

dplyr::bind_rows(list_data)

do.call(rbind, list_data)
```

