---
title: "Ch.01"
format: html
---

第1章　フリーソフトウェアRの基礎
　1.1　コンソール画面での計算
　　1.1.1　スクリプトでプログラムを書く
　1.2　ファイルの読み書き
　1.3　関数の利用
　1.4　高精度なグラフィックス機能
　1.5　パッケージのインストール
　1.6　プログラミングの処理文

第Ⅰ部　企業経営の数量的評価手法
 
第2章　回帰分析
　2.1　回帰分析の基本
　2.2　企業経営への回帰分析の適用
　2.3　ロジスティック回帰分析
　2.4　経営・財務指標
 
第3章　DEAアプローチ
　3.1　DEAの概略
　3.2　DEAの計算ソフト
　3.3　数値例
 
第4章　SFA手法
　4.1　SFAの概略
　4.2　パッケージの利用と数値例
　4.3　各都道府県の生産効率性評価
 
第5章　SCM手法による政策評価

 
第6章　クラスター分析と判別分析
　6.1　クラスター分析
　6.2　判別分析
　6.3　企業経営への判別分析の応用
　6.4　Support Vector Machine
　6.5　One-Class SVMによる異常値の検知

第Ⅱ部　金融市場における計量分析
 
第7章　理財ツールおよびリスク管理
　7.1　ポートフォリオの最適化
　7.2　オプションとBlack-Scholes公式
　7.3　極値理論と応用例
　　7.3.1　極値理論の応用
 
第8章　金融時系列転換点の検出
　8.1　マーケットの急激な変動
　8.2　転換点を検出する必要性
　8.3　CP検出の数理的手法
　8.4　数値シミュレーションおよび実証分析
　　8.4.1　数値シミュレーション結果
　　　実証分析の結果
　　　　GBPの場合／VaR-GBP／USDの場合／VaR-USD
 
第9章　ベイズ推定
　　　　共役分布／将来のイベントの予測／適切な事前分布の選択尺度
　9.1　サンプリング手法について
　　　　ギブスサンプラー (Gibbs Sampler) ／MHアルゴリズム
　　9.1.1　パッケージrstan
 
第10章　ベイジアン手法の応用
　10.1　モデルの記述
　10.2　数値シミュレーションの結果
　10.3　株価時系列データの転換点の検出
　10.4　SDEにおける構造変化の検出
　　10.4.1　Jump-Diffusion SDEについて
　　10.4.2　ジャンプ拡散 (Jump-Diffusion) SDEの具体例
　　10.4.3　数値実験の結果
　　10.4.4　ポートフォリオの構成に与える影響
　10.5　通信トラフィック転換点の検出
　　10.5.1　DoS攻撃と通信トラフィック
　　10.5.2　数値実験
　　10.5.3　実測通信トラフィック解析及びその転換点の検出
　　10.5.4　解析結果のまとめ
　　　　回線Aについて
　　10.5.5　曜日ごとの解析結果
　　　　A回線の曜日ごとの基本統計量
　　10.5.6　転換点の検出
　10.6　COVID-19の新規感染者数の例
　　10.6.1　実証分析の結果
　　　　ドイツのケース／イタリアのケース／オーストリアのケース
　10.7　ISによるレア・イベントの測定
　　10.7.1　IS法によるレア・イベントの確率の測定
　　10.7.2　重点サンプリング (Importance Function) の決め方
　　10.7.3　数値例
 
第11章　MRSA手法による実証分析
　11.1　MRSA手法の概要
　11.2　実証分析の結果
　　11.2.1　ドイツのCOVID-19の新規感染者数の状況
　　11.2.2　MRSAの解析およびその結果
　　11.2.3　COVID-19増加率について
　11.3　GARCHモデルへの適用
　　11.3.1　GARCHモデルをDAX収益率への適用
　　11.3.2　COVID-19の増加率をGARCHへ適用した結果
　11.4　ボラティリティを用いたMRSA解析の結果
　
　
