---
title: "Ch.12"
output: html_document
date: "2023-08-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
binom.test(c(13, 7), p = 1/2)
```

```{r}
d <- c(152, 39, 53, 6)

chisq.test(d, p = c(9,3,3,1), rescale.p = T)
# or chisq.test(d, p = c(9,3,3,1)/16)

pchisq(8.9724, df = 3, lower.tail = FALSE)
qchisq(0.95, df = 3)

```

```{r}
egg <- c(rep(0, 0), rep(1, 0), rep(2, 60), rep(3, 101), rep(4, 84), rep(5, 48), rep(6, 7), rep(7, 0), rep(8, 0))

r <- hist(egg, br = seq(-0.5, 9.5, 1), main = "Histgram of egg distribution")
x <- 0:9

pois <- length(egg) * dpois(x, mean(egg))
lines(r$mids, pois)

res_tab <- rbind(r$counts, pois)

rownames(res_tab) <- c("obs", "exp")
colnames(res_tab) <- r$mids
res_tab

res_tab[, 8] <- res_tab[, 8] + res_tab[, 9] + res_tab[, 10]
tab2 <- res_tab[, 1:8]
tab2
obs <- as.vector(tab2["obs", ])
exp <- as.vector(tab2["exp", ])

chisq.test(obs, p = exp, rescale.p = TRUE)
pchisq(105.86, df = 6, lower.tail = FALSE)
```

```{r}
chisq.test(obs, p = exp, rescale.p = TRUE, simulate.p.value = TRUE, B = 10000)
```

## 12.4 $\chi^2$ 独立性検定

```{r}

x <- matrix(c(25, 15, 10, 30), nrow = 2, ncol = 2, byrow = TRUE)

chisq.test(x)
chisq.test(x, correct = FALSE)
```

## 12.5 $\chi^2$ 独立性検定 vs. 分割表の対数尤度比検定（G検定）：その比較

```{r}
library(Deducer)

hair <- matrix(c(32, 43, 16, 9, 55, 65, 64, 16), nrow = 2, ncol = 4, byrow = TRUE)
chisq.test(hair)

likelihood.test(hair)
```

## 12.6 フィッシャーの正確確率法

```{r}

cal_exaxt_test <- function(a, b, c, d) {
  
  numer <- factorial(a+b) * factorial(c+d) * factorial(a+c) * factorial(b+d)
  denom <- factorial(a+b+c+d) * factorial(a) * factorial(b) * factorial(c) * factorial(d)
  
  return(numer / denom)
  
}

a <- cal_exaxt_test(12, 7, 2, 9)
b <- cal_exaxt_test(13, 6, 1, 10)
c <- cal_exaxt_test(14, 5, 0, 11)

a + b + c
```

```{r}
fisher.test(matrix(c(12, 7, 2, 9), nrow = 2, ncol = 2, byrow = TRUE), alternative = "g")
```

```{r}
d <- matrix(c(54, 10325, 25, 51790), nrow = 2, ncol = 2, byrow = TRUE)
fisher.test(d, or = TRUE, conf.level = 0.95)
```
