---
title: "Ch.13"
output: html_document
date: "2023-08-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## 

```{r}
d1 <- c(44, 48, 36, 32, 51, 45, 54,56)
d2 <- c(32, 40, 44, 44, 34, 30, 26)

wilcox.test(d1, d2)
```

```{r}
library(exactRankTests)
wilcox.test(d1, d2)
```


## 2標本の位置母数の検定：フリグナー・ポリセロ検定とブルネル・ムンツェル検定
```{r}
dA <- c(10.3, 10.6, 10.9, 10.9, 10.9, 11.0, 11.2, 12.0, 12.0, 12.5, 12.6, 12.6, 14.2, 14.6, 15.0, 15.6)
dB <- c(12.1, 12.1, 12.2, 12.4, 12.4, 12.6, 12.7, 12.8, 12.9, 13.0, 13.0, 13.0, 13.0, 13.4, 13.5, 13.6, 13.7, 13.7, 13.9, 13.9, 13.9, 14.0, 14.0)

var.test(dA, dB)
```
```{r}
library(car)

d <- data.frame(
  score = c(dA, dB),
  group = c(rep("a", 16), rep("b", 23))
)

leveneTest(d$score ~ factor(d$group))
```
```{r}
library(NSM3)
pFligPoli(dA, dB, method = NA, n.mc = 10000)
```
```{r}
library(lawstat)
brunner.munzel.test(dA, dB)
```

## 13.3 3つの標本の順位和の検定
```{r}
d1 <- c(14.0, 12.1, 9.6, 8.2, 10.2)
d2 <- c(8.4, 5.1, 5.5, 6.6, 6.3)
d3 <- c(6.9, 7.3, 5.8, 4.1, 5.4)

kruskal.test(list(d1, d2, d3))
```

```{r}
d1 <- c(7.68, 7.69, 7.70, 7.70, 7.72, 7.73, 7.73, 7.76)
d2 <- c(7.71, 7.73, 7.74, 7.74, 7.78, 7.78, 7.80, 7.81)
d3 <- c(7.74, 7.75, 7.77, 7.78, 7.80, 7.81, 7.84)
d4 <- c(7.71, 7.71, 7.74, 7.79, 7.81, 7.85, 7.87, 7.91)

kruskal.test(list(d1, d2, d3, d4))
```

## 13.4 ネメニィ・ダン検定とスチール・ドワス検定
```{r}
library(PMCMRplus)

d1 <- c(14.0, 12.1, 9.6, 8.2, 10.2)
d2 <- c(8.4, 5.1, 5.5, 6.6, 6.3)
d3 <- c(6.9, 7.3, 5.8, 4.1, 5.4)

kwAllPairsNemenyiTest(list(d1, d2, d3))

```

```{r}
Steel.Dwass <- function(data,                                                # データベクトル
                        group)                                          # 群変数ベクトル
{
        OK <- complete.cases(data, group)                            # 欠損値を持つケースを除く
        data <- data[OK]
        group <- group[OK]
        n.i <- table(group)                                          # 各群のデータ数
        ng <- length(n.i)                                            # 群の数
        t <- combn(ng, 2, function(ij) {
                i <- ij[1]
                j <- ij[2]
                r <- rank(c(data[group == i], data[group == j]))     # 群 i, j をまとめてランク付け
                R <- sum(r[1:n.i[i]])                                        # 検定統計量
                N <- n.i[i]+n.i[j]                                   # 二群のデータ数の合計
                E <- n.i[i]*(N+1)/2                                  # 検定統計量の期待値
                V <- n.i[i]*n.i[j]/(N*(N-1))*(sum(r^2)-N*(N+1)^2/4)  # 検定統計量の分散
                return(abs(R-E)/sqrt(V))                                # t 値を返す
        })
        p <- ptukey(t*sqrt(2), ng, Inf, lower.tail=FALSE)            # P 値を計算
        result <- cbind(t, p)                                                # 結果をまとめる
        rownames(result) <- combn(ng, 2, paste, collapse=":")
        return(result)
}


data <- c(6.9, 7.5, 8.5, 8.4, 8.1, 8.7, 8.9, 8.2, 7.8, 7.3, 6.8, # 第 1 群のデータ，11 例
          9.6, 9.4, 9.5, 8.5, 9.4, 9.9, 8.7, 8.1, 7.8, 8.8,      # 第 2 群のデータ，10 例
          5.7, 6.4, 6.8, 7.8, 7.6, 7.0, 7.7, 7.5, 6.8, 5.9,      # 第 3 群のデータ，10 例
          7.6, 8.7, 8.5, 8.5, 9.0, 9.2, 9.3, 8.0, 7.2, 7.9, 7.8  # 第 4 群のデータ，11 例
          )
group <- rep(1:4, c(11, 10, 10, 11))                     # 群の識別変数
Steel.Dwass(data, group)
```

```{r}
d <- read.csv("sample/table13-9.csv")

plot(d$a, d$b)
```

```{r}
cor(d$a, d$b, method = "s")
cor.test(d$a, d$b, method = "s")
```

```{r}
d <- read.csv("sample/table13-10.csv")
plot(d$math, d$biol)
```
```{r}
cor.test(d$math, d$biol, method = "p")
cor.test(d$math, d$biol, method = "s")
```
#> 
#> 
 